name: Arsenic
version: '1.2.0'
main: de.miskynet.arsenic.Main
api-version: '1.21'
authors: [ MiSkynet ]
description: A Shop plugin
commands:
  shop:
    description: Open the shop
    usage: /shop
    permission: arsenic.shop
    aliases: [ s ]
  arsenic:
    description: A admin command
    usage: /arsenic
    permission: arsenic.arsenic